# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_todo = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Todo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_todo.setIcon(icon)
        self.btn_todo.setObjectName("btn_todo")
        self.gridLayout.addWidget(self.btn_todo, 8, 4, 1, 1)
        self.lbl_profit = QtWidgets.QLabel(self.centralwidget)
        self.lbl_profit.setObjectName("lbl_profit")
        self.gridLayout.addWidget(self.lbl_profit, 5, 4, 1, 1)
        self.lbl_buy = QtWidgets.QLabel(self.centralwidget)
        self.lbl_buy.setObjectName("lbl_buy")
        self.gridLayout.addWidget(self.lbl_buy, 3, 4, 1, 1)
        self.lbl_date = QtWidgets.QLabel(self.centralwidget)
        self.lbl_date.setObjectName("lbl_date")
        self.gridLayout.addWidget(self.lbl_date, 2, 4, 1, 1)
        self.lbl_sell = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sell.setObjectName("lbl_sell")
        self.gridLayout.addWidget(self.lbl_sell, 4, 4, 1, 1)
        self.btn_delete_record = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Delete_record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_record.setIcon(icon1)
        self.btn_delete_record.setObjectName("btn_delete_record")
        self.gridLayout.addWidget(self.btn_delete_record, 7, 4, 1, 1)
        self.btn_suggestions = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Suggestions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_suggestions.setIcon(icon2)
        self.btn_suggestions.setObjectName("btn_suggestions")
        self.gridLayout.addWidget(self.btn_suggestions, 0, 1, 1, 1)
        self.btn_statistics = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_statistics.setIcon(icon3)
        self.btn_statistics.setObjectName("btn_statistics")
        self.gridLayout.addWidget(self.btn_statistics, 0, 0, 1, 1)
        self.btn_about_us = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/About_us.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about_us.setIcon(icon4)
        self.btn_about_us.setObjectName("btn_about_us")
        self.gridLayout.addWidget(self.btn_about_us, 0, 3, 1, 1)
        self.btn_contact_us = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Contact_us.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_contact_us.setIcon(icon5)
        self.btn_contact_us.setObjectName("btn_contact_us")
        self.gridLayout.addWidget(self.btn_contact_us, 0, 2, 1, 1)
        self.btn_add_record = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Add_record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_record.setIcon(icon6)
        self.btn_add_record.setObjectName("btn_add_record")
        self.gridLayout.addWidget(self.btn_add_record, 6, 4, 1, 1)
        self.tbl_widget_existing_records = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_widget_existing_records.setObjectName("tbl_widget_existing_records")
        self.tbl_widget_existing_records.setColumnCount(0)
        self.tbl_widget_existing_records.setRowCount(0)
        self.gridLayout.addWidget(self.tbl_widget_existing_records, 2, 0, 6, 4)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh.setIcon(icon7)
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout.addWidget(self.btn_refresh, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Journal"))
        self.btn_todo.setToolTip(_translate("MainWindow", "Press \"T\""))
        self.btn_todo.setText(_translate("MainWindow", "Todo"))
        self.lbl_profit.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Profit: 0</span></p></body></html>"))
        self.lbl_buy.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Buy: 0</span></p></body></html>"))
        self.lbl_date.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Date: DD/MM/YYYY</span></p></body></html>"))
        self.lbl_sell.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Sell: 0</span></p></body></html>"))
        self.btn_delete_record.setToolTip(_translate("MainWindow", "Press \"D\""))
        self.btn_delete_record.setText(_translate("MainWindow", "Delete Record"))
        self.btn_suggestions.setToolTip(_translate("MainWindow", "Press \"E\""))
        self.btn_suggestions.setText(_translate("MainWindow", "Estimation"))
        self.btn_statistics.setToolTip(_translate("MainWindow", "Press \"S\""))
        self.btn_statistics.setText(_translate("MainWindow", "Statistics"))
        self.btn_about_us.setToolTip(_translate("MainWindow", "Press \"B\""))
        self.btn_about_us.setText(_translate("MainWindow", "About us"))
        self.btn_contact_us.setToolTip(_translate("MainWindow", "Press \"C\""))
        self.btn_contact_us.setText(_translate("MainWindow", "Contact us"))
        self.btn_add_record.setToolTip(_translate("MainWindow", "Press \"A\""))
        self.btn_add_record.setText(_translate("MainWindow", "Add record"))
        self.btn_refresh.setToolTip(_translate("MainWindow", "Press \"R\""))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))

from icons import icons_rc
